import json, os, sys, tomllib

# usage: palette.py [out_dir]
# Reads palette.toml, fails if a pair the desktop draws one on the other reads badly, and writes
# the palette out in the forms the theme forks take (THEMING.md):
#   construct.json         everything, flat
#   construct.css          custom properties, dark by default and light under prefers-color-scheme
#   construct.scss         Orchis' variables: the accent per variant and the background scale
#   bibata-render.json     the entries for Bibata's render.json
# The other generators import load() instead of copying hex values.
HERE = os.path.dirname(os.path.abspath(__file__))


def load(path=os.path.join(HERE, "palette.toml")):
    with open(path, "rb") as f:
        return tomllib.load(f)


def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def luminance(h):
    lin = lambda c: c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (lin(c / 255) for c in rgb(h))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def orchis_on_dark(h):
    """Whether Orchis' on() puts dark text on this color (its brightness test, _colors.scss)."""
    r, g, b = rgb(h)
    return (r * 299 + g * 587 + b * 114) / 1000 >= 156


# Orchis' dark text on a bright fill: black at 0.87, over white (the lightest it is drawn on).
ORCHIS_DARK_TEXT = "#212121"

# WCAG 2.2: 4.5 for text, 3 for parts of the interface that are not text; 7 for body text,
# which is read the most.
TEXT, UI, BODY = 4.5, 3.0, 7.0


def checks(p):
    n = p["neutral"]
    for mode, bg, view in (("dark", n["e"], n["g"]), ("light", n["c"], n["a"])):
        m = p[mode]
        for surface, s in (("background", bg), ("view", view)):
            yield f"{mode} text on {surface}", m["text"], s, BODY
            yield f"{mode} muted on {surface}", m["muted"], s, TEXT
            yield f"{mode} accent on {surface} (links)", m["accent"], s, TEXT
            for k in ("success", "warning", "error"):
                yield f"{mode} {k} on {surface}", m[k], s, TEXT
        yield f"{mode} text on accent", m["on_accent"], m["accent"], TEXT
        # Buttons filled with a semantic color (destructive, success): Orchis puts black or white
        # on them by brightness, as on the accent.
        for k in ("success", "warning", "error"):
            yield f"{mode} text on {k} fill", ORCHIS_DARK_TEXT if orchis_on_dark(m[k]) else "#FFFFFF", m[k], TEXT
    yield "folder glyph on folder", p["icons"]["folder_glyph"], p["icons"]["folder"], UI
    yield "folder on dark background", p["icons"]["folder"], n["e"], UI
    yield "cursor outline on fill", p["cursor"]["outline"], p["cursor"]["fill"], UI
    yield "mark on boot", p["brand"]["cyan"], p["brand"]["boot"], BODY


def validate(p):
    problems, report = [], []
    for name, fg, bg, need in checks(p):
        c = contrast(fg, bg)
        report.append(f"  {c:5.2f}  {'ok ' if c >= need else 'LOW'} (>= {need})  {name}")
        if c < need:
            problems.append(f"{name}: {fg} on {bg} is {c:.2f}:1, needs {need}:1")
    for mode in ("dark", "light"):  # Orchis picks the text on the accent itself: it must agree
        m = p[mode]
        if orchis_on_dark(m["accent"]) != (luminance(m["on_accent"]) < 0.5):
            problems.append(f"{mode}: Orchis would put {'dark' if orchis_on_dark(m['accent']) else 'white'} "
                            f"text on {m['accent']}, the palette says {m['on_accent']}")
    return problems, report


def flat(p):
    return {f"{group}-{k}".replace("_", "-"): v for group, d in p.items() for k, v in d.items()}


def css(p):
    n = p["neutral"]
    def block(mode, bg, view, raised, alt):
        m = p[mode]
        rows = {"bg": bg, "view": view, "raised": raised, "alt": alt, **{k.replace("_", "-"): v for k, v in m.items()}}
        return "\n".join(f"  --{k}: {v};" for k, v in rows.items())
    dark = block("dark", n["e"], n["g"], n["h"], n["f"])
    light = block("light", n["c"], n["a"], n["a"], n["b"])
    brand = "\n".join(f"  --{k}: {v};" for k, v in flat({g: p[g] for g in ("brand", "neutral", "icons", "cursor")}).items())
    fonts = (f'  --font-wordmark: "{p["type"]["wordmark"]}", sans-serif;\n'
             f'  --font-ui: "{p["type"]["ui"]}", system-ui, sans-serif;\n'
             f'  --font-mono: "{p["type"]["mono"]}", ui-monospace, monospace;')
    return (f"/* Generated by palette.py from palette.toml - do not edit. */\n"
            f":root {{\n{brand}\n{fonts}\n  color-scheme: dark;\n{dark}\n}}\n"
            f"@media (prefers-color-scheme: light) {{\n  :root:not([data-mode=\"dark\"]) {{\n    color-scheme: light;\n"
            + "\n".join("  " + l for l in light.splitlines()) + "\n  }\n}\n"
            f":root[data-mode=\"light\"] {{\n  color-scheme: light;\n{light}\n}}\n"
            f":root[data-mode=\"dark\"] {{\n  color-scheme: dark;\n{dark}\n}}\n")


def scss(p):
    n, d, l = p["neutral"], p["dark"], p["light"]
    # Orchis names a color's two shades by what they are, not where they go: theme() takes
    # $<color>-light for the dark variant and $<color>-dark for the light one.
    lines = ["// Generated by palette.py from palette.toml - do not edit.",
             "// Orchis: the accent as a theme color ('construct'), and the background scale.",
             f"$construct-light: {d['accent']}; // accent in the dark variant",
             f"$construct-dark: {l['accent']}; // accent in the light variant",
             ""]
    lines += [f"$construct-bg-{k}: {v};" for k, v in n.items()]
    lines += ["", "// Semantic colors, dark and light variant"]
    for k in ("success", "warning", "error"):
        lines += [f"$construct-{k}-light: {d[k]};", f"$construct-{k}-dark: {l[k]};"]
    return "\n".join(lines) + "\n"


def bibata(p):
    c = p["cursor"]
    colors = [{"match": "#00FF00", "replace": c["fill"].upper()},
              {"match": "#0000FF", "replace": c["outline"].upper()},
              {"match": "#FF0000", "replace": c["watch"].upper()}]
    return {f"Bibata-Modern-Construct{side}": {"dir": f"svg/modern{side.lower()}",
                                              "out": f"bitmaps/Bibata-Modern-Construct{side}",
                                              "colors": colors}
            for side in ("", "-Right")}


if __name__ == "__main__":
    OUT = sys.argv[1] if len(sys.argv) > 1 else "palette"
    p = load()
    problems, report = validate(p)
    print("contrast:\n" + "\n".join(report))
    if problems:
        sys.exit("palette.toml:\n  " + "\n  ".join(problems))
    os.makedirs(OUT, exist_ok=True)
    json.dump(flat(p), open(f"{OUT}/construct.json", "w"), indent=1)
    open(f"{OUT}/construct.css", "w").write(css(p))
    open(f"{OUT}/construct.scss", "w").write(scss(p))
    json.dump(bibata(p), open(f"{OUT}/bibata-render.json", "w"), indent=2)
    print(f"{OUT}/: construct.json, construct.css, construct.scss, bibata-render.json")
